name: WakaTime Readme

on:
  workflow_dispatch:
  schedule:
    - cron: "5 22 * * *"

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_TOKEN }}
          COMMIT_MESSAGE: Update Wakatime stats
          BLOCKS: "â¬œðŸŸ¨ðŸŸ©"
          TIME_RANGE: last_7_days
          SHOW_TIME: true
